"""Ajuste a campos boleanos de tabla trabajador y empresas

Revision ID: 390550456a56
Revises: 9aee16e57b5e
Create Date: 2026-06-30 09:34:09.186635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390550456a56'
down_revision = '9aee16e57b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
