"""create empresas table

Revision ID: 6386f0979705
Revises: ac61bba70966
Create Date: 2026-06-29 11:45:08.815270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6386f0979705'
down_revision = 'ac61bba70966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('representante', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('domicilio', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.drop_column('dom_fiscal')

    with op.batch_alter_table('dim_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'dim_empresas', ['empresa_id'], ['id'])
        batch_op.drop_column('nom_empresa')

    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dim_empresas', ['empresa_id'], ['id'])
        batch_op.drop_column('proyecto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dim_servicios', ['proyecto_id'], ['id'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('dim_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_empresa', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dom_fiscal', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('telefono')
        batch_op.drop_column('correo')
        batch_op.drop_column('domicilio')
        batch_op.drop_column('representante')

    # ### end Alembic commands ###
