"""Ajuste a campo ROL de usuarios para poder manejar accesos por rol de usuario

Revision ID: 864e9a6489b0
Revises: b75d28ed94ef
Create Date: 2026-07-01 16:42:52.982970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864e9a6489b0'
down_revision = 'b75d28ed94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=30), nullable=False))
        batch_op.drop_column('tipo_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_usuario', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
