"""Se añade campo de fecha de alta y baja de trabajadores

Revision ID: 90deb2271de4
Revises: 390550456a56
Create Date: 2026-06-30 16:07:51.801342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90deb2271de4'
down_revision = '390550456a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_alta', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_baja', sa.Date(), nullable=True))

    with op.batch_alter_table('dim_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('fecha_alta')

    # ### end Alembic commands ###
