"""Se añade campos regimen fiscal y boleano si es activa la empresa o no

Revision ID: 9aee16e57b5e
Revises: 9ea35252c913
Create Date: 2026-06-30 09:26:17.340059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aee16e57b5e'
down_revision = '9ea35252c913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimen_fiscal', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('regimen_fiscal')

    # ### end Alembic commands ###
