"""Se añade campo nivel a tabla de empresas

Revision ID: 9ea35252c913
Revises: 
Create Date: 2026-06-30 09:22:20.913319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea35252c913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_empresas', schema=None) as batch_op:
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
