"""Se agrega columna encargado a la tabla de trabajadores

Revision ID: b75d28ed94ef
Revises: cc3499ff2f7d
Create Date: 2026-06-30 17:33:50.123959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75d28ed94ef'
down_revision = 'cc3499ff2f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encargado', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.drop_column('encargado')

    # ### end Alembic commands ###
