"""Se cambia columna de fecha de ingreso de los trabajadores

Revision ID: cc3499ff2f7d
Revises: 90deb2271de4
Create Date: 2026-06-30 17:32:37.723343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3499ff2f7d'
down_revision = '90deb2271de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', sa.Date(), nullable=True))
        batch_op.drop_column('fecha_alta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_alta', sa.DATE(), nullable=True))
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###
